# coding=utf-8

import PIL.Image


class Const(object):

    APP_NAME = "crackclean"
    APP_CONSOLE_DEFAULT_UPDATE_PERIOD_MS = 200
    APP_GUI_DEFAULT_UPDATE_PERIOD_MS = 200
    APP_PROC_CHECK_MIN_INTERVAL_S = (1000 / 1000)

    CMD_SYNC_TIMEOUT_MS = 3000
    CMD_SYNC_WARN_MS = 15

    CMD_QUEUE_MAXSIZE = 8
    RESP_QUEUE_MAXSIZE = 8
    EVENT_QUEUE_MAXSIZE = 8
    QUEUE_TIMEOUT_S = 2
    ENDPOINT_QUEUE_SHUTDOWN_DELAY_S = 0.5

    MAIN_CONTROLLER_MIN_PERIOD_S = (5 / 1000)

    LABEL_PATH = 'etc/crack_labels.txt'
    MODEL_PATH = 'etc/optimizedQ_123214_tpu.tflite'

#    CALIBRATION_LG_MM = 438
#    CALIBRATION_GUID_CENTER_X_PX = 23
#    CALIBRATION_SCALING_FACTOR = 0.8722466960352423
#    ACTUATOR_MM_AT_Y_ORIGIN = 161.4		# TODO: rough approximation

    CALIBRATION_LG_MM = 460.0
    CALIBRATION_GUID_CENTER_X_PX = 23
    CALIBRATION_SCALING_FACTOR = (200.0 / 233.0)    # mm/px
    CALIBRATION_ACTUATOR_MM_AT_Y_ORIGIN = 176.0		# TODO: rough approximation

    DETECTION_CRACK_BOX_DEFAULT = [0, 40, 299, 139]
    DETECTION_DETECT_THRESH_DEFAULT = 0.55
    DETECTION_SIMPFILTER_THRESH_DEFAULT = 45
    DETECTION_ADAPTFILTER_THRESH_DEFAULT = 0.29
    DETECTION_ADAPTFILTER_RADIUS_DEFAULT = 14
    DETECTION_IMG_DIM = 300
    DETECTION_LABEL_CRACK = 'crack'
    DETECTION_LABEL_CIRCLE = 'circle'
    DETECTION_LABEL_SQUARE = 'square'
    DETECTION_PIL_IMG_MODE = 'L'
    DETECTION_PIL_RESAMP = PIL.Image.ANTIALIAS

    CAMERA_STREAM_CHANNEL_PACKET_SIZE = 9000
    CAMERA_STREAM_CHANNEL_PACKET_DELAY = 400
    CAMERA_PIXEL_FORMAT = 'Mono8'		# TODO: do we want Mono8?
    CAMERA_VIDEO_MODE = 'Mode2'			# TODO: do we want Mode1 or Mode2?
    CAMERA_WIDTH = 480				# depends on CAMERA_VIDEO_MODE
    CAMERA_HEIGHT = 480				# depends on CAMERA_VIDEO_MODE
    CAMERA_OFFSET_X = 0				# depends on CAMERA_VIDEO_MODE and CAMERA_WIDTH
    CAMERA_OFFSET_Y = 0				# depends on CAMERA_VIDEO_MODE and CAMERA_HEIGHT
    VIDEO_MAX_IMG_REQ_DELAY_S = 1.0

    JOYSTICK_COOKED_DEV = '/dev/input/by-id/usb-CH_Products_MEGATRON_USB_Joystick-joystick'
    JOYSTICK_MAX_OPEN_ATTEMPTS = 16
    JOYSTICK_OPEN_FAIL_SLEEP_S = (500 / 1000)

    JOYSTICK_AXIS_NUM = 0
    JOYSTICK_BUTTON_NUM = 0
    JOYSTICK_POSITIVE_IS_EXTEND = True
    JOYSTICK_INITIAL_IGNORE_TIME_S = (500 / 1000)	# to ignore the initial flurry of non-init events that the kernel/device occasionally emits
    JOYSTICK_CONTROLLER_LOOP_SLEEP_S = (5 / 1000)
    JOYSTICK_ZERO_MAX_NORM = 0.02

    JRKG2_DEV = '/dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_G2_18v19_00259610-if01'
    JRKG2_BAUD = None				# use None for direct-USB interface
    JRKG2_READ_TIMEOUT_MS = 250
    JRKG2_WRITE_TIMEOUT_MS = 250
    JRKG2_CRC_ENABLED = True
    JRKG2_CHECK_ERRFLAGS_AFTER_CMDS = True
    ACTUATOR_STROKE_MM = 12 * 25.4

